### ISSUE TITLE
bro

### ISSUE THREAD

**Issue by Raid4152** [dem4ply/chibi_dl_tmo#1]
and the guide?

**Comment by dem4ply** [comment]
here you got https://github.com/dem4ply/chibi_dl_tmo#install

for the moment is not working becuase depend of undetected-chromedriver and i commit the stupid mistake of update all my sistem and undetected-chromedriver only work with the version 114

other problem can have is the change of the domain to "visortmo.com" now have another extra step to get the id of the chapter
